import { sticker } from '../lib/sticker.js'

let handler = async (m, { conn, text, usedPrefix, command }) => {

let stiker = await sticker(null, global.API(`${pickRandom(upinipin)}`), global.packname, global.author)
    if (stiker) return conn.sendFile(m.chat, stiker, 'sticker.webp', '', m)
    throw stiker.toString()
    
}
  handler.command = /^(upinipin)$/i
  handler.tags = ['sticker']
  handler.help = ['upinipin']
  handler.limit = true
  //handler.private = true 
  
  export default handler
function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}
  
  global.upinipin = [
"https://i.ibb.co/Wg846jf/bangbang-sticker-1.png",
"https://i.ibb.co/vY8fvMg/bangbang-sticker-3.png",
"https://i.ibb.co/y8zp9Qq/bangbang-sticker-4.png",
"https://i.ibb.co/dpgLHsc/bangbang-sticker-5.png",
"https://i.ibb.co/98DSrJV/bangbang-sticker-6.png",
"https://i.ibb.co/fqd67bZ/bangbang-sticker-8.png",
"https://i.ibb.co/PZhMh3N/bangbang-sticker.png",
"https://i.ibb.co/7JMxQW9/couplekiss-woman-woman-sticker-1.png",
"https://i.ibb.co/4gWbMJf/couplekiss-woman-woman-sticker-2.png",
"https://i.ibb.co/WGyCMVP/couplekiss-woman-woman-sticker-4.png",
"https://i.ibb.co/dpW0T5p/couplekiss-woman-woman-sticker-5.png",
"https://i.ibb.co/HNFmqf9/couplekiss-woman-woman-sticker-6.png",
"https://i.ibb.co/D1F0D13/couplekiss-woman-woman-sticker-7.png",
"https://i.ibb.co/GcqZfnv/couplekiss-woman-woman-sticker-8.png",
"https://i.ibb.co/n0427sG/couplekiss-woman-woman-sticker-9.png",
"https://i.ibb.co/DWfqvng/couplekiss-woman-woman-sticker.png",
"https://i.ibb.co/vLFfR72/sunflower-sticker.png",
"https://i.ibb.co/VWKpT5N/Tg-Sticker-0912da97.png",
"https://i.ibb.co/J3PX1MT/Tg-Sticker-1789216f.png",
"https://i.ibb.co/FzgkP6P/Tg-Sticker-1cc59fc6.png",
"https://i.ibb.co/WngmY02/Tg-Sticker-1d64f638.png",
"https://i.ibb.co/ZzYWmCm/Tg-Sticker-1e306188.png",
"https://i.ibb.co/g43wDgL/Tg-Sticker-239be3e3.png",
"https://i.ibb.co/XbMYZvt/Tg-Sticker-274aab76.png",
"https://i.ibb.co/3NKkDrH/Tg-Sticker-2a62796c.png",
"https://i.ibb.co/gzJVT0f/Tg-Sticker-2e45e1d4.png",
"https://i.ibb.co/st2Q8TC/Tg-Sticker-325d7a9d.png",
"https://i.ibb.co/s5wPZGX/Tg-Sticker-34355e5f.png",
"https://i.ibb.co/K5YSBqy/Tg-Sticker-37bd669c.png",
"https://i.ibb.co/SXDH34J/Tg-Sticker-38d32e94.png",
"https://i.ibb.co/Mgcs7Q7/Tg-Sticker-3ca54b60.png",
"https://i.ibb.co/j6xLxpf/Tg-Sticker-43a9afcd.png",
"https://i.ibb.co/qrhs2r8/Tg-Sticker-4e1422d9.png",
"https://i.ibb.co/TKHtd4k/Tg-Sticker-4e593fbb.png",
"https://i.ibb.co/fSwrC9s/Tg-Sticker-512892b4.png",
"https://i.ibb.co/jG2m9Gf/Tg-Sticker-530ae4c2.png",
"https://i.ibb.co/R35p5Ky/Tg-Sticker-552d1b9b.png",
"https://i.ibb.co/NVfmj73/Tg-Sticker-5a38a492.png",
"https://i.ibb.co/z5tNc8g/Tg-Sticker-5b304fcb.png",
"https://i.ibb.co/Dghsq43/Tg-Sticker-6a1e5121.png",
"https://i.ibb.co/2hkpYgP/Tg-Sticker-6e488ee1.png",
"https://i.ibb.co/p1BJkCL/Tg-Sticker-6ed353f8.png",
"https://i.ibb.co/fx8qYmL/Tg-Sticker-76dcd731.png",
"https://i.ibb.co/q9gFFsw/Tg-Sticker-8ac7a06d.png",
"https://i.ibb.co/RcGMZ4b/Tg-Sticker-8f180432.png",
"https://i.ibb.co/ygMYqQB/Tg-Sticker-9311938b.png",
"https://i.ibb.co/GWbLBB9/Tg-Sticker-96436643.png",
"https://i.ibb.co/NtMW2q5/Tg-Sticker-9698d12d.png",
"https://i.ibb.co/8bgb9gb/Tg-Sticker-98d3a148.png",
"https://i.ibb.co/ggpyZTd/Tg-Sticker-99b3022f.png",
"https://i.ibb.co/2nntgyB/Tg-Sticker-9affb184.png",
"https://i.ibb.co/DbqG0hQ/Tg-Sticker-9c2575c0.png",
"https://i.ibb.co/jzL3D72/Tg-Sticker-9dbca3fa.png",
"https://i.ibb.co/M92VH7c/Tg-Sticker-9fcc51a8.png",
"https://i.ibb.co/n3CYHYy/Tg-Sticker-a8976a66.png",
"https://i.ibb.co/QkYW2mJ/Tg-Sticker-a97562b7.png",
"https://i.ibb.co/WkcBbGp/Tg-Sticker-abf42eeb.png",
"https://i.ibb.co/S5SBnS6/Tg-Sticker-b0a5e7ff.png",
"https://i.ibb.co/Ydz38zW/Tg-Sticker-b4ff7ad7.png",
"https://i.ibb.co/8dBfGXQ/Tg-Sticker-b8e46eba.png",
"https://i.ibb.co/0s9GjWT/Tg-Sticker-b99492d1.png",
"https://i.ibb.co/g6XX2Fk/Tg-Sticker-bba0e64a.png",
"https://i.ibb.co/s6xC4MP/Tg-Sticker-c47d0883.png",
"https://i.ibb.co/kMgcW5P/Tg-Sticker-c57d3aee.png",
"https://i.ibb.co/zHSrYxk/Tg-Sticker-caeac27c.png",
"https://i.ibb.co/hKvBg84/Tg-Sticker-ccc2ae30.png",
"https://i.ibb.co/16wG5Qx/Tg-Sticker-cd9bab46.png",
"https://i.ibb.co/N7fbDLD/Tg-Sticker-ce849eda.png",
"https://i.ibb.co/kDJn78S/Tg-Sticker-ced0bf85.png",
"https://i.ibb.co/hc6LRsn/Tg-Sticker-cff72017.png",
"https://i.ibb.co/tcgBdXN/Tg-Sticker-d19a56d5.png",
"https://i.ibb.co/ZHwp7Tx/Tg-Sticker-d3d821fd.png",
"https://i.ibb.co/p3Q0bww/Tg-Sticker-df02b99d.png",
"https://i.ibb.co/xgcpGDD/Tg-Sticker-df9e9264.png",
"https://i.ibb.co/SR14kkG/Tg-Sticker-e0505966.png",
"https://i.ibb.co/3dSCY0N/Tg-Sticker-effe49af.png",
"https://i.ibb.co/tZhL4Br/Tg-Sticker-f0acaad8.png",
"https://i.ibb.co/w6kSWct/Tg-Sticker-f5a15a63.png",
"https://i.ibb.co/4Zrh3NS/Tg-Sticker-fac9fcc9.png",
"https://i.ibb.co/DfNG5Z1/Tg-Sticker-fb98d6da.png",
"https://i.ibb.co/d68spGD/undefined-sticker-1.png",
"https://i.ibb.co/FY6fyLn/undefined-sticker-10.png",
"https://i.ibb.co/rxZX3CB/undefined-sticker-11.png",
"https://i.ibb.co/wgC17pG/undefined-sticker-12.png",
"https://i.ibb.co/NrCbQfb/undefined-sticker-13.png",
"https://i.ibb.co/Wt09sFS/undefined-sticker-14.png",
"https://i.ibb.co/prn8Z0d/undefined-sticker-15.png",
"https://i.ibb.co/X28R40d/undefined-sticker-16.png",
"https://i.ibb.co/x2rz4ZS/undefined-sticker-17.png",
"https://i.ibb.co/19bSZLr/undefined-sticker-18.png",
"https://i.ibb.co/fVWhyV0/undefined-sticker-19.png",
"https://i.ibb.co/B2V8NH9/undefined-sticker-2.png",
"https://i.ibb.co/8b9FZg1/undefined-sticker-20.png",
"https://i.ibb.co/k4SyfNP/undefined-sticker-21.png",
"https://i.ibb.co/tpPJd7q/undefined-sticker-22.png",
"https://i.ibb.co/RNt22bd/undefined-sticker-23.png",
"https://i.ibb.co/kg0HqTs/undefined-sticker-24.png",
"https://i.ibb.co/hVC0qYk/undefined-sticker-25.png",
"https://i.ibb.co/mhSNmKL/undefined-sticker-3.png",
"https://i.ibb.co/Bjtpd4N/undefined-sticker-4.png",
"https://i.ibb.co/CmjWsbv/undefined-sticker-5.png",
"https://i.ibb.co/z5QYdrF/undefined-sticker-6.png",
"https://i.ibb.co/Wp7gqD5/undefined-sticker-7.png",
"https://i.ibb.co/z63NYhT/undefined-sticker-8.png",
"https://i.ibb.co/27NkzZF/undefined-sticker-9.png",
"https://i.ibb.co/vBBj1qm/undefined-sticker.png",
"https://i.ibb.co/2MKN9z0/couplekiss-woman-woman-sticker-3.png"
  ]